// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/new-energy-monitoring/internal/api/handler"
	"github.com/new-energy-monitoring/internal/application/service"
	"github.com/new-energy-monitoring/internal/infrastructure/persistence"
)

import (
	_ "github.com/new-energy-monitoring/docs"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序
// Wire 会自动生成这个函数的实现
func InitializeApp() (*App, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(config)
	if err != nil {
		return nil, err
	}
	database, err := NewDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	redisClient, err := NewRedis(config, logger)
	if err != nil {
		return nil, err
	}
	kafkaProducer, err := NewKafka(config, logger)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewUserRepository(database)
	roleRepository := persistence.NewRoleRepository(database)
	permissionRepository := persistence.NewPermissionRepository(database)
	operationLogRepository := persistence.NewOperationLogRepository(database)
	jwtManager := NewJWTManager(config)
	passwordManager := NewPasswordManager(config)
	authService := service.NewAuthService(userRepository, roleRepository, permissionRepository, operationLogRepository, jwtManager, passwordManager)
	authHandler := handler.NewAuthHandler(authService)
	userService := service.NewUserService(userRepository, roleRepository, operationLogRepository, passwordManager)
	userHandler := handler.NewUserHandler(userService)
	deviceRepository := persistence.NewDeviceRepository(database)
	pointRepository := persistence.NewPointRepository(database)
	deviceService := service.NewDeviceService(deviceRepository, pointRepository)
	deviceHandler := handler.NewDeviceHandler(deviceService)
	alarmRepository := persistence.NewAlarmRepository(database)
	alarmService := service.NewAlarmService(alarmRepository)
	alarmHandler := handler.NewAlarmHandler(alarmService)
	alarmRuleRepository := persistence.NewAlarmRuleRepository(database)
	alarmRuleService := service.NewAlarmRuleService(alarmRuleRepository)
	alarmRuleHandler := handler.NewAlarmRuleHandler(alarmRuleService)
	stationRepository := persistence.NewStationRepository(database)
	stationService := service.NewStationService(stationRepository, deviceRepository, pointRepository)
	stationHandler := handler.NewStationHandler(stationService)
	regionRepository := persistence.NewRegionRepository(database)
	subRegionRepository := persistence.NewSubRegionRepository(database)
	regionService := service.NewRegionService(regionRepository, subRegionRepository)
	regionHandler := handler.NewRegionHandler(regionService)
	pointService := service.NewPointService(pointRepository)
	pointHandler := handler.NewPointHandler(pointService)
	qaRepository := persistence.NewQARepository(database)
	dialogueManager := NewDialogueManager()
	qaService := service.NewQAService(qaRepository, dialogueManager)
	qaHandler := handler.NewQAHandler(qaService)
	systemConfigRepository := persistence.NewSystemConfigRepository(database)
	configService := service.NewConfigService(systemConfigRepository, operationLogRepository)
	configHandler := handler.NewConfigHandler(configService)
	notificationConfigRepository := persistence.NewNotificationConfigRepository(database)
	notificationConfigService := service.NewNotificationConfigService(notificationConfigRepository)
	notificationConfigHandler := handler.NewNotificationConfigHandler(notificationConfigService)
	exportServiceInterface := service.NewExportService(alarmRepository, deviceRepository, stationRepository)
	exportHandler := handler.NewExportHandler(exportServiceInterface)
	reportService := service.NewReportService()
	reportHandler := handler.NewReportHandler(reportService)
	operationLogService := service.NewOperationLogService(operationLogRepository)
	operationLogHandler := handler.NewOperationLogHandler(operationLogService)
	energyEfficiencyRepository := persistence.NewEnergyEfficiencyRepository(database)
	energyEfficiencyService := service.NewEnergyEfficiencyService(energyEfficiencyRepository)
	energyEfficiencyHandler := handler.NewEnergyEfficiencyHandler(energyEfficiencyService)
	workOrderRepository := persistence.NewWorkOrderRepository(database)
	workOrderService := service.NewWorkOrderService(workOrderRepository, deviceRepository)
	workOrderHandler := handler.NewWorkOrderHandler(workOrderService)
	inventoryRepository := persistence.NewInventoryRepository(database)
	inventoryTransactionRepository := persistence.NewInventoryTransactionRepository(database)
	supplierRepository := persistence.NewSupplierRepository(database)
	inventoryService := service.NewInventoryService(inventoryRepository, inventoryTransactionRepository, supplierRepository)
	inventoryHandler := handler.NewInventoryHandler(inventoryService)
	purchaseOrderRepository := persistence.NewPurchaseOrderRepository(database)
	purchaseOrderService := service.NewPurchaseOrderService(purchaseOrderRepository, supplierRepository)
	purchaseOrderHandler := handler.NewPurchaseOrderHandler(purchaseOrderService)
	receiptRepository := persistence.NewReceiptRepository(database)
	receiptService := service.NewReceiptService(receiptRepository, purchaseOrderRepository, inventoryRepository, inventoryTransactionRepository)
	receiptHandler := handler.NewReceiptHandler(receiptService)
	costCategoryRepository := persistence.NewCostCategoryRepository(database)
	costCategoryService := service.NewCostCategoryService(costCategoryRepository)
	costCategoryHandler := handler.NewCostCategoryHandler(costCategoryService)
	costEntryRepository := persistence.NewCostEntryRepository(database)
	costEntryService := service.NewCostEntryService(costEntryRepository, costCategoryRepository)
	costEntryHandler := handler.NewCostEntryHandler(costEntryService)
	costAllocationRepository := persistence.NewCostAllocationRepository(database)
	costAllocationService := service.NewCostAllocationService(costAllocationRepository, costEntryRepository)
	costAllocationHandler := handler.NewCostAllocationHandler(costAllocationService)
	costReportRepository := persistence.NewCostReportRepository(database)
	costReportService := service.NewCostReportService(costReportRepository, costEntryRepository)
	costReportHandler := handler.NewCostReportHandler(costReportService)
	assetRepository := persistence.NewAssetRepository(database)
	assetMaintenanceRepository := persistence.NewAssetMaintenanceRepository(database)
	assetDepreciationRepository := persistence.NewAssetDepreciationRepository(database)
	assetDocumentRepository := persistence.NewAssetDocumentRepository(database)
	assetService := service.NewAssetService(assetRepository, assetMaintenanceRepository, assetDepreciationRepository, assetDocumentRepository)
	assetHandler := handler.NewAssetHandler(assetService)
	assetMaintenanceService := service.NewAssetMaintenanceService(assetMaintenanceRepository, assetRepository)
	assetMaintenanceHandler := handler.NewAssetMaintenanceHandler(assetMaintenanceService)
	assetDepreciationService := service.NewAssetDepreciationService(assetDepreciationRepository, assetRepository)
	assetDepreciationHandler := handler.NewAssetDepreciationHandler(assetDepreciationService)
	assetDocumentService := service.NewAssetDocumentService(assetDocumentRepository, assetRepository)
	assetDocumentHandler := handler.NewAssetDocumentHandler(assetDocumentService)
	server := NewHTTPServer(config, authHandler, userHandler, deviceHandler, alarmHandler, alarmRuleHandler, stationHandler, regionHandler, pointHandler, qaHandler, configHandler, notificationConfigHandler, exportHandler, reportHandler, operationLogHandler, energyEfficiencyHandler, workOrderHandler, inventoryHandler, purchaseOrderHandler, receiptHandler, costCategoryHandler, costEntryHandler, costAllocationHandler, costReportHandler, assetHandler, assetMaintenanceHandler, assetDepreciationHandler, assetDocumentHandler)
	app := NewApp(config, logger, database, redisClient, kafkaProducer, server)
	return app, nil
}
