apiVersion: v1
kind: Service
metadata:
  name: {{ include "new-energy-monitoring.fullname" . }}-api-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "new-energy-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
  {{- with .Values.apiServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.apiServer.service.type "NodePort") .Values.apiServer.service.nodePort }}
      nodePort: {{ .Values.apiServer.service.nodePort }}
      {{- end }}
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "new-energy-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
